Changes for PowerAPI monitoring

diff --git a/.github/workflows/changelog_verifier.yml b/.github/workflows/changelog_verifier.yml
--- a/.github/workflows/changelog_verifier.yml
+++ b/.github/workflows/changelog_verifier.yml
@@ -1,44 +1,38 @@
-name: "Changelog Verifier"
-on:
-  pull_request:
-    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
-
 jobs:
-  # Enforces the update of a changelog file on every pull request
   verify-changelog:
     if: github.repository == 'opensearch-project/OpenSearch'
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          ref: ${{ github.event.pull_request.head.sha }}
-      - uses: dangoslen/changelog-enforcer@v3
-        id: verify-changelog-3x
-        with:
-          skipLabels: "autocut, skip-changelog"
-          changeLogPath: 'CHANGELOG-3.0.md'
-        continue-on-error: true
-      - uses: dangoslen/changelog-enforcer@v3
-        id: verify-changelog
-        with:
-          skipLabels: "autocut, skip-changelog"
-          changeLogPath: 'CHANGELOG.md'
-        continue-on-error: true
-      - run: |
-          # The check was possibly skipped leading to success for both the jobs
-          if [[ ${{ steps.verify-changelog-3x.outcome }} == 'success' && ${{ steps.verify-changelog.outcome }} == 'success' ]]; then
-            exit 0
-          fi
-          
-          if [[ ${{ steps.verify-changelog-3x.outcome }} == 'failure' && ${{ steps.verify-changelog.outcome }} == 'failure' ]]; then
-            echo "error: Please ensure a changelog entry exists in CHANGELOG.md or CHANGELOG-3.0.md"
-            exit 1
-          fi
-          
-          # Concatenates the labels and checks if the string contains "backport"
-          has_backport_label=${{ contains(join(github.event.pull_request.labels.*.name, ', '), 'backport')}}
-          if [[ ${{ steps.verify-changelog.outcome }} == 'success' && $has_backport_label == false ]]; then
-            echo "error: Please make sure that the PR has a backport label associated with it when making an entry to the CHANGELOG.md file"
-            exit 1
-          fi
+    - continue-on-error: true
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+        token: ${{ secrets.GITHUB_TOKEN }}
+    - continue-on-error: true
+      id: verify-changelog-3x
+      uses: dangoslen/changelog-enforcer@v3
+      with:
+        changeLogPath: CHANGELOG-3.0.md
+        skipLabels: autocut, skip-changelog
+    - continue-on-error: true
+      id: verify-changelog
+      uses: dangoslen/changelog-enforcer@v3
+      with:
+        changeLogPath: CHANGELOG.md
+        skipLabels: autocut, skip-changelog
+    - continue-on-error: true
+      run: "# The check was possibly skipped leading to success for both the jobs\n\
+        if [[ ${{ steps.verify-changelog-3x.outcome }} == 'success' && ${{ steps.verify-changelog.outcome\
+        \ }} == 'success' ]]; then\n  exit 0\nfi\n\nif [[ ${{ steps.verify-changelog-3x.outcome\
+        \ }} == 'failure' && ${{ steps.verify-changelog.outcome }} == 'failure' ]];\
+        \ then\n  echo \"error: Please ensure a changelog entry exists in CHANGELOG.md\
+        \ or CHANGELOG-3.0.md\"\n  exit 1\nfi\n\n# Concatenates the labels and checks\
+        \ if the string contains \"backport\"\nhas_backport_label=${{ contains(join(github.event.pull_request.labels.*.name,\
+        \ ', '), 'backport')}}\nif [[ ${{ steps.verify-changelog.outcome }} == 'success'\
+        \ && $has_backport_label == false ]]; then\n  echo \"error: Please make sure\
+        \ that the PR has a backport label associated with it when making an entry\
+        \ to the CHANGELOG.md file\"\n  exit 1\nfi\n"
+name: Changelog Verifier
+on:
+  repository_dispatch:
+    types: trigger-ga___changelog_verifier.yml
